### ISSUE TITLE
autoloader shaders

### ISSUE THREAD

**Issue by jywarren** [jywarren/fisheyegl#12]
Hi @ccpandhare, can you post a PR of your changes which make shader loading automatic? Thanks!

**Comment by ccpandhare** [comment]
Yes, sure!
But the method I used was using `require()`. Which means, we will also have to use grunt/gulp and browserify for that. I wasn't sure if that's a good idea, because currently fisheyegl doesn't use that and hence, I was hesistant in opening a PR until now.

Should we go ahead with that?

Basically, I was just converting the shader files to require-able NodeJS Modules like this:

```js
module.exports = "\
CONTENT\n\
OF\n\
THE\n\
SHADER\n\
FILE\n\
";
```

And then using browserify to bundle this up for the web.

**Comment by ccpandhare** [comment]
The benefit of this is that no HTTP requests are generated (So no CORS Error problems) and the user doesn't have to include additional files in their codebase if they wish to use default shaders.

So what do you think?

**Comment by jywarren** [comment]
Yes please! It sounds great!

**Comment by ccpandhare** [comment]
Okay then! I shall work on this!
